# Generated by Django 5.0.1 on 2024-02-01 01:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_secret', models.TextField(verbose_name='Текст секрета')),
                ('encrypted_passphrase', models.CharField(max_length=255, verbose_name='Секретная фраза')),
                ('secret_key', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Секретный ключ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('iv', models.CharField(max_length=255, verbose_name='Вектор инициализации')),
            ],
        ),
    ]
