# Generated by Django 5.0.1 on 2024-02-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysecrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активност'),
        ),
    ]
